### ISSUE TITLE
[Feature Request] Fallback to the current file directory if there is no active project

### ISSUE THREAD

**Issue by Spiker985** [mauricioszabo/generic-lsp#9]
It looks like the [init-lsp function](https://github.com/mauricioszabo/generic-lsp/blob/e85c5db3fc0cb7d4ffa5e501c7c588dd56770d52/src/generic_lsp/commands.cljs#L77) uses the project directory to set the `workspaceFolders` for the lsp server.

It may make sense to fall back to `atom.workspace.getActiveTextEditor().getDirectoryPath()` and `atom.workspace.getActiveTextEditor().getFileName()` if `atom.project.getPaths()` is empty - in the event that someone only has a single file open, but would still like to use a LSP.

**Comment by mauricioszabo** [comment]
I would be possible, BUT - at least clojure-lsp, rust-analyzer and clangd all expect to see some specific files on the workspace path. So, while it would allow you to _run_ the LSP server, it will probably not be useful and it'll report weird, invalid, and confusing things...
